name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nbdev
      - run: conda install pybind11 suitesparse
      - uses: Jan-David-Black/fastai-workflows@master
        with:
          enable_git_lfs: true
